### ISSUE TITLE
On mac compile fails

### ISSUE THREAD

**Issue by grigorovich** [ue4plugins/TextAsset#1]
UE4.15P4, MacOS 10.12.3, Latest Xcode.
Another plugins compiles fine. But i want to try that TextAsset. So

Log:
```
ogInit:Warning: Incompatible or missing module: UE4Editor-TextAsset.dylib
LogInit:Warning: Incompatible or missing module: UE4Editor-TextAssetEditor.dylib

Running Mono...

Setting up Mono
/Users/Shared/UnrealEngine/4.15/Engine /Users/Shared/UnrealEngine/4.15/Engine/Binaries/Mac
Messages while compiling /Users/mbargo/Documents/Projects/Unreal/!_Experiments/Temp415copy/Intermediate/Build/BuildRules/Temp415copyModuleRules.dll:
/Users/mbargo/Documents/Projects/Unreal/!_Experiments/Temp415copy/Plugins/TextAsset/Source/TextAsset/TextAsset.Build.cs(7,50) : error CS1729: The type `UnrealBuildTool.ModuleRules' does not contain a constructor that takes `1' arguments
(0,0) : error : /Users/Shared/UnrealEngine/4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe (Location of the symbol related to previous error)
/Users/mbargo/Documents/Projects/Unreal/!_Experiments/Temp415copy/Plugins/TextAsset/Source/TextAssetEditor/TextAssetEditor.Build.cs(7,55) : error CS1729: The type `UnrealBuildTool.ModuleRules' does not contain a constructor that takes `1' arguments
(0,0) : error : /Users/Shared/UnrealEngine/4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe (Location of the symbol related to previous error)
ERROR: UnrealBuildTool encountered an error while compiling source files
LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAsset.dylib
LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAssetEditor.dylib
LogExit: Preparing to exit.
```

TextAsset.Build.cs(7,50)
TextAssetEditor.Build.cs(7,55)
Both at in line with " : Base (Target)"

is it absent constructor?

**Comment by gmpreussner** [comment]
Make sure you pull the commit tagged with "4.15". The Master revision only works with upcoming 4.16 code.

**Comment by grigorovich** [comment]
Sure. 4.15 Preview 3 and Preview 4.

**Comment by grigorovich** [comment]
I've checked on latest branch 4.15 and the log is same.

**Comment by gmpreussner** [comment]
You didn't read what I wrote :)

Please pull the [tag](https://github.com/ue4plugins/TextAsset/tags) that matches your Engine version.

**Comment by grigorovich** [comment]
I read and i know all what you wrote and :] 
Ive use Your TextAsset from branch "master" with tag "4.15" here, in UE4.15 Preview4 on Mac. That's correct.
But on mac its doesn't works. Compile failed. 
And one moment. Today i tried with latest commit and log not same:


```
Running Mono...

Setting up Mono
/Users/Shared/UnrealEngine/4.15/Engine /Users/Shared/UnrealEngine/4.15/Engine/Binaries/Mac
Compiling with MacOSX SDK 10.12
@progress push 5%
ERROR: All source files in module "TextAssetEditor" must include the same precompiled header first.  Currently "/Users/Shared/UnrealEngine/4.15/Engine/Source/Editor/UnrealEd/Public/Toolkits/AssetEditorToolkit.h" is included by most of the source files.  The following source files are not including "/Users/Shared/UnrealEngine/4.15/Engine/Source/Editor/UnrealEd/Public/Toolkits/AssetEditorToolkit.h" as their first include:

/Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/AssetTools/TextAssetActions.cpp (including /Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/AssetTools/TextAssetActions.h)
/Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Factories/TextAssetFactory.cpp (including /Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Factories/TextAssetFactory.h)
/Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Factories/TextAssetFactoryNew.cpp (including /Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Factories/TextAssetFactoryNew.h)
/Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Toolkits/TextAssetEditorToolkit.cpp (including /Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Toolkits/TextAssetEditorToolkit.h)
/Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Widgets/STextAssetEditor.cpp (including /Users/user/Projects/UnrealEngine/!_Experiments/Temp415cpp/Plugins/TextAsset/Source/TextAssetEditor/Private/Widgets/STextAssetEditor.h)

LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAsset.dylib
LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAssetEditor.dylib
LogExit: Preparing to exit. 
```

Btw, there folder name is "TextAsset-4.15" instead of "TextAsset" in release zip archive. Each archive for different version of UE (i think).

PS: i put TextAsset to Plugins of project folder (not in Engine)

**Comment by gmpreussner** [comment]
I just recreated the 4.15 tag, as well as the 4.15 release, because there were indeed compilation errors. Could you please try again?

Please note that the latest commit requires 4.16, so you have to go back to the one called [Reverted build rules changes to fix 4.15 release](https://github.com/ue4plugins/TextAsset/commit/7edd5702c50eaf6d2c6f01fc0413c9f67fb85545).

**Comment by grigorovich** [comment]
Yes, i read all headers of commits. 
I will try right now

**Comment by grigorovich** [comment]
Same log:
"ERROR: All source files in module "TextAssetEditor" must include the same precompiled header first." etc. 

I will try your next commit at once. // or wait for binary 4.16 preview :]

**Comment by gmpreussner** [comment]
I was able to repro. Looks like PCH handling changed last minute. Please make it an Engine plug-in for now. Project plug-ins will require some different Build.cs settings that I still need to figure out.

**Comment by grigorovich** [comment]
I did:
1. Update UE to 4.15 release (today)
2. Put TextAsset (4.15 tagged) to Engine/Plugins/Media/
3. Run UE and create clean cpp project
4. UE Warning Window: "Plugin Missing... Compile? Yes" >> "Plugin missing. Disable?"

Log:
```
Running Mono...

Setting up Mono
/Users/Shared/UnrealEngine/4.15/Engine /Users/Shared/UnrealEngine/4.15/Engine/Binaries/Mac
Compiling with MacOSX SDK 10.12
@progress push 5%
@progress pop
Target is up to date
Deploying TestTextEditor Mac Development...
Deploying now!
Total build time: 5.50 seconds (NoActionsToExecute executor: 0.00 seconds)
LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAsset.dylib
LogInit:Warning: Still incompatible or missing module: UE4Editor-TextAssetEditor.dylib
LogExit: Preparing to exit.
```
So sounds like the UE did not touch sources of plugin. 

That method (Engine/Plugins/) works with compiled binaries only. I think

**Comment by gmpreussner** [comment]
Engine plug-ins will only be compiled if you compile the Engine from source. It doesn't work with binary-only UE4 builds. We don't compile Engine plug-in source when running binary builds.

Since you don't compile the whole Engine, the only way to make this work is to put the plug-in into your project's Plugin directory. I'm currently working on fixing support for that. There is a new setting that is now required... you could try adding it in TextAsset.Build.cs and TextAssetEditor.Build.cs

`PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs`

I will test it and update the code shortly.

**Comment by grigorovich** [comment]
Failed.
Anyway i forked your repo for self and create branch specially for mac's experiments.

**Comment by grigorovich** [comment]
On 4.16 Preview 3 works well (compiled). After compile ue has ability to create "Text asset".

**Comment by gmpreussner** [comment]
Hooray, thanks for looking into it!
